/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'f' at '16-5-23 下午4:48' with Gradle 2.7
 *
 * @author f, @date 16-5-23 下午4:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
