V1="value-of-v1"
VBool1=yes
VT_$(VBool1)=yes
!VBool2=yes
VT_$(VBool2)=yes

all :
	echo $(V1)
	echo $(VBool1)
	echo "VT_$(VBool1)"
	echo $(VT_$(VBool1))
	echo $(VBool2)
	echo "VT_$(VBool2)"
	echo $(VT_$(VBool2))
